#!/usr/bin/env python3
"""Embed canonical hardware profiles so the CLI installs as one executable."""
from pathlib import Path
import json
import base64
root = Path(__file__).resolve().parents[1]
profiles = [json.loads(p.read_text()) for p in sorted((root / "calibrations").glob("*.json"))]
data = json.dumps(profiles, separators=(",", ":")).encode()
encoded = base64.b64encode(data).decode()
output = "// Generated by Scripts/generate-calibrations.py; edit calibrations/*.json instead.\nimport Foundation\n\nenum BundledCalibrationData {\n    static let json = Data(base64Encoded: \"" + encoded + "\")!\n}\n"
(root / "Sources/NanoleafCore/BundledCalibrations.generated.swift").write_text(output)
